version: "3"

services:
  app:
    build: .
    command: sh -c "uvicorn main:app --reload --host=0.0.0.0"
    ports:
      - 8000:8000
    volumes:
      - .:/app
    networks:
      - app-network
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h catalog -p 5432 -q -U catalog-admin"]
      interval: 10s
      timeout: 5s
      retries: 3

  postgres:
    image: postgres:latest

    environment:
      POSTGRES_DB: catalog
      POSTGRES_USER: catalog-admin
      POSTGRES_PASSWORD: 1234
    ports:
      - 5432:5432
    networks:
      - app-network

networks:
  app-network:
